- include: debian.yml

- name: Check if DynamoDB is installed
  stat:
    path: /opt/dynamodb_{{ dynamodb_version }}/DynamoDBLocal.jar
  register: install_check

- name: Download the DynamoDB local jar
  get_url:
   url: http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_{{ dynamodb_version }}.tar.gz
   checksum: sha256:{{ dynamodb_sha }}
   dest: /tmp/dynamodb_local_{{ dynamodb_version }}.tar.gz
  notify:
   - Restart DynamoDB
  when: not install_check.stat.exists

- name: ensure directory
  file:
   path: /opt/dynamodb_{{ dynamodb_version }}
   state: directory
  when: not install_check.stat.exists

- name: Unarchive
  unarchive:
   copy: no
   src: /tmp/dynamodb_local_{{ dynamodb_version }}.tar.gz
   dest: /opt/dynamodb_{{ dynamodb_version }}
   creates: /opt/dynamodb_{{ dynamodb_version }}/DynamoDBLocal.jar
  when: not install_check.stat.exists

- name: "Drop an init file for DynamoDB"
  template: >
    src=dynamodb.conf
    dest=/etc/init/dynamodb.conf
    mode=0700
    owner=root
    group=root
  notify:
    - Restart DynamoDB

- name: "Make sure DynamoDB local development is running"
  service: >
    name=dynamodb
    state=started
